### ISSUE TITLE
Tons of syntax issues and unnecessary comments

### ISSUE THREAD

**Issue by 00100000** [pokemymom/project-stuff#2]
add me as a contributor and I can help. I know you don't trust me as much as Kevin, but I'm a fellow developer and I can help!

**Comment by pokemymom** [comment]
how can u help

**Comment by 00100000** [comment]
I... know how to code and use github? I can edit your projects if u write garbage code.

**Comment by 00100000** [comment]
I might even add a .gitignore if u use IntelliJ or something

**Comment by PatheticMustan** [comment]
yes

**Comment by pokemymom** [comment]
YES WHAT
